name: Deploy ML Model Web App

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: SSH into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd Predictive-Maintenance
            git pull origin main
            docker rm -f $(docker ps -aq)
            docker rmi -f $(docker images -aq)
            docker-compose build
            docker-compose up -d
          
      # - name: update changes in codebase
      #   run: |
      #     cd Predictive-Maintenance
      #     git pull origin main

      # - name: remove old docker compose containers and images
      #   run: |
      #     docker rm -f $(docker ps -aq)
      #     docker rmi -f $(docker images -aq)
          
      # - name: build docker compose container
      #   run: |
      #     docker-compose build
      #     docker-compose up -d
        




